---
language: ruby
branches:
    only:
        - master
env:
   global:
    - DEST_ID=nsent
    - NSVER=7
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e VERSIONS_PACK
        -e STAGES_PACK
        -e UPLOAD_DEST
        "

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils xsltproc python-libxml2 intltool expect

script: make

