---
language: ruby
branches:
    only:
        - master
env:
   global:
    - DEST_ID=nsent
    - NSVER=7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils xsltproc python-libxml2 intltool expect

script: make

deploy:
    skip_cleanup: true
    provider: script
    script: bash scripts/upload.sh
    on:
        branch: master

